namespace Model.Dto

type RegisteredKeys = {
    ORIGINAL_IMAGE_DIRECTORY: string
    ORIGINAL_IMAGE_CROPPING_DIRECTORY: string
    TEMP_LOWRES_IMAGE_FOLDER_PATH: string
    DOWNSCALED_UPSCALED_IMAGE_FOLDER_PATH: string
    LABELS_ARRAY_FOLDER_PATH: string
    TELEGRAM_BOT_ID: string
    CHAT_ID: int64
};